const PRODUCTS = [
  {
    id: 1,
    name: "Gelang Manik (Beaded Bracelet)",
    category: "bbeads",
    desc: "Sentuhan Manis untuk Pergelangan Tanganmu! ✨</br>Percantik penampilan harianmu dengan gelang manik handmade kami. Didesain dengan perpaduan warna yang lembut dan material berkualitas, gelang ini cocok banget untuk stacking (tumpuk) atau dipakai sendiri sebagai pemanis.</br>Material: Glass beads premium & tali elastis kuat.</br>Ukuran: Standar 16cm (bisa custom ukuran).",
    price: "0",
    stock: "- pcs",
    origin: "Estetik & Minimalis",
    badge: "new",
    image: "src/img/bracelet1.jpg",
    colors: ["#fff"],
    shape: "round"
  },
  {
    id: 2,
    name: "Gantungan HP (Strap Phone)",
    category: "strap",
    desc: "Bikin HP Kamu Makin Kiyowo & Anti-Mainstream! 📱🌈</br>Capek dengan tampilan HP yang itu-itu saja? Tambahkan Phone Charm manik ini! Selain bikin HP kamu makin cantik buat mirror selfie, gantungan ini juga memudahkanmu menggenggam HP agar tidak mudah slip.</br>Detail: Menggunakan perpaduan manik mutiara, akrilik, dan aksen charm lucu.</br>Kegunaan: Bisa dipasang di lubang case HP mana saja.</br>Vibe: Y2K, Soft Girl, atau Vibrant Pop.",
    price: "0",
    stock: "- pcs",
    origin: "Trendy & Pop Culture",
    badge: "new",
    image: "src/img/strap1.webp",
    colors: ["#fff"],
    shape: "round"
  },
  {
    id: 3,
    name: "Natural Stone Bracelet",
    category: "naturalstone",
    desc: "Koleksi Gelang Batu Alam Asli ✨🌿</br>Hadirkan kesan mewah namun tetap membumi dengan gelang yang terbuat dari batuan alam pilihan. Setiap butiran batu memiliki corak unik yang tidak akan pernah sama satu dengan lainnya—sama spesialnya dengan dirimu.</br>Material: 100% Batu Alam Asli (seperti Amethyst, Rose Quartz, Tiger Eye, atau Black Onyx).</br>Detail: Menggunakan tali elastis berkualitas tinggi atau pengait berbahan stainless steel.</br>Gaya: Sangat cocok untuk gaya kasual maupun formal, memberikan kesan dewasa dan eksklusif.",
    price: "0",
    stock: "- pcs",
    origin: "Elegan, Earthy & Bermakna",
    badge: "new",
    image: "src/img/batualam1.webp",
    colors: ["#fff"],
    shape: "round"
  },
  {
    id: 4,
    name: "Bag Charm",
    category: "bagcharm",
    desc: "Ubah Tas Polos Jadi Luar Biasa! 🎒✨</br>Berikan karakter pada tas sekolah, tas kerja, atau tote bag kamu dengan Gantungan Tas Manik eksklusif ini. Hadir dengan desain yang lebih berani dan ukuran manik yang bervariasi untuk menciptakan tekstur yang unik.</br>Material: Manik akrilik tebal & pengait besi anti-karat (Lobster Claw).</br>Gaya: Perpaduan warna kontras yang bikin tas kamu langsung jadi pusat perhatian.",
    price: "0",
    stock: "- pcs",
    origin: "Playful & Pernak-Pernik",
    badge: "new",
    image: "src/img/bagcharm1.jpg",
    colors: ["#fff"],
    shape: "round"
  },
  {
    id: 6,
    name: "Gelang Manik (Beaded Bracelet)",
    category: "bbeads",
    desc: "Elegan dalam kesederhanaan ✨</br>Gelang manik ini hadir dengan nuansa warna soft yang calming, cocok banget buat kamu yang suka tampilan minimal tapi tetap standout.</br>Material: Glass beads premium & tali elastis kuat.</br>Perfect for: Daily wear, mix & match, atau hadiah manis untuk orang tersayang 💗",
    price: "0",
    stock: "- pcs",
    origin: "Estetik & Minimalis",
    badge: "new",
    image: "src/img/bracelet3.jpg",
    colors: ["#fff"],
    shape: "round"
  },
  {
    id: 7,
    name: "Gelang Manik (Beaded Bracelet)",
    category: "bbeads",
    desc: "Playful tapi tetap classy 🌸</br>Perpaduan warna yang lebih hidup bikin gelang ini cocok jadi statement kecil di pergelangan tanganmu.</br>Material: Glass beads premium & tali elastis tahan lama.</br>Style: Cocok untuk outfit casual, hangout, atau layering biar makin gemoy ✨",
    price: "0",
    stock: "- pcs",
    origin: "Estetik & Minimalis",
    badge: "new",
    image: "src/img/bracelet4.jpg",
    colors: ["#fff"],
    shape: "round"
  },
  {
    id: 8,
    name: "Strap Phone",
    category: "strap",
    desc: "Simple but eye-catching 📱✨</br>Strap ini dirancang untuk kamu yang suka aksesoris clean tapi tetap punya karakter.</br>Detail: Manik pilihan + aksen lucu yang subtle.</br>Fungsi: Anti slip + bikin HP kamu lebih stylish saat dibawa kemana-mana 💗",
    price: "0",
    stock: "- pcs",
    origin: "Trendy & Pop Culture",
    badge: "new",
    image: "src/img/strap2.jpg",
    colors: ["#fff"],
    shape: "round"
  },
  {
    id: 9,
    name: "Strap Phone",
    category: "strap",
    desc: "Cute overload alert 💖</br>Desain yang lebih playful dengan kombinasi warna cerah, cocok buat kamu yang suka tampil beda.</br>Detail: Mix beads + charm lucu yang bikin HP kamu makin hidup.</br>Vibe: Y2K, girly, dan super fun ✨",
    price: "0",
    stock: "- pcs",
    origin: "Trendy & Pop Culture",
    badge: "new",
    image: "src/img/strap3.png",
    colors: ["#fff"],
    shape: "round"
  },
  {
    id: 10,
    name: "Strap Phone",
    category: "strap",
    desc: "Bold & expressive 🌈</br>Buat kamu yang suka tampil standout, strap ini hadir dengan warna dan desain yang lebih berani.</br>Detail: Kombinasi beads kontras + finishing rapi.</br>Perfect for: Mirror selfie, OOTD, dan jadi pusat perhatian 😤✨",
    price: "0",
    stock: "- pcs",
    origin: "Trendy & Pop Culture",
    badge: "new",
    image: "src/img/strap4.webp",
    colors: ["#fff"],
    shape: "round"
  }
];