window.PRODUCTS = [
  {
    id: 1,
    name: "Gelang Manik (Beaded Bracelet)",
    category: "bbeads",
    desc: "Sentuhan Manis untuk Pergelangan Tanganmu! ✨</br>Percantik penampilan harianmu dengan gelang manik handmade kami. Didesain dengan perpaduan warna yang lembut dan material berkualitas, gelang ini cocok banget untuk stacking (tumpuk) atau dipakai sendiri sebagai pemanis.</br>Material: Glass beads premium & tali elastis kuat.</br>Ukuran: Standar 16cm (bisa custom ukuran).",
    price: "0",
    stock: "- pcs",
    origin: "Estetik & Minimalis",
    badge: "new",
    image: "src/img/bracelet/bracelet1.jpg",
    colors: ["#fff"],
    shape: "round"
  },
  {
    id: 2,
    name: "Gantungan HP (Strap Phone)",
    category: "strap",
    desc: "Bikin HP Kamu Makin Kiyowo & Anti-Mainstream! 📱🌈</br>Capek dengan tampilan HP yang itu-itu saja? Tambahkan Phone Charm manik ini! Selain bikin HP kamu makin cantik buat mirror selfie, gantungan ini juga memudahkanmu menggenggam HP agar tidak mudah slip.</br>Detail: Menggunakan perpaduan manik mutiara, akrilik, dan aksen charm lucu.</br>Kegunaan: Bisa dipasang di lubang case HP mana saja.</br>Vibe: Y2K, Soft Girl, atau Vibrant Pop.",
    price: "0",
    stock: "- pcs",
    origin: "Trendy & Pop Culture",
    badge: "new",
    image: "src/img/strap/strap1.webp",
    colors: ["#fff"],
    shape: "round"
  },
  {
    id: 3,
    name: "Natural Stone Bracelet",
    category: "naturalstone",
    desc: "Koleksi Gelang Batu Alam Asli ✨🌿</br>Hadirkan kesan mewah namun tetap membumi dengan gelang yang terbuat dari batuan alam pilihan. Setiap butiran batu memiliki corak unik yang tidak akan pernah sama satu dengan lainnya—sama spesialnya dengan dirimu.</br>Material: 100% Batu Alam Asli (seperti Amethyst, Rose Quartz, Tiger Eye, atau Black Onyx).</br>Detail: Menggunakan tali elastis berkualitas tinggi atau pengait berbahan stainless steel.</br>Gaya: Sangat cocok untuk gaya kasual maupun formal, memberikan kesan dewasa dan eksklusif.",
    price: "0",
    stock: "- pcs",
    origin: "Elegan, Earthy & Bermakna",
    badge: "new",
    image: "src/img/batualam/batualam1.webp",
    colors: ["#fff"],
    shape: "round"
  },
  {
    id: 4,
    name: "Bag Charm",
    category: "bagcharm",
    desc: "Ubah Tas Polos Jadi Luar Biasa! 🎒✨</br>Berikan karakter pada tas sekolah, tas kerja, atau tote bag kamu dengan Gantungan Tas Manik eksklusif ini. Hadir dengan desain yang lebih berani dan ukuran manik yang bervariasi untuk menciptakan tekstur yang unik.</br>Material: Manik akrilik tebal & pengait besi anti-karat (Lobster Claw).</br>Gaya: Perpaduan warna kontras yang bikin tas kamu langsung jadi pusat perhatian.",
    price: "0",
    stock: "- pcs",
    origin: "Playful & Pernak-Pernik",
    badge: "new",
    image: "src/img/bagcharm/bagcharm1.jpg",
    colors: ["#fff"],
    shape: "round"
  },
  {
    id: 6,
    name: "Gelang Manik (Beaded Bracelet)",
    category: "bbeads",
    desc: "Elegan dalam kesederhanaan ✨</br>Gelang manik ini hadir dengan nuansa warna soft yang calming, cocok banget buat kamu yang suka tampilan minimal tapi tetap standout.</br>Material: Glass beads premium & tali elastis kuat.</br>Perfect for: Daily wear, mix & match, atau hadiah manis untuk orang tersayang 💗",
    price: "0",
    stock: "- pcs",
    origin: "Estetik & Minimalis",
    badge: "new",
    image: "src/img/bracelet/bracelet3.jpg",
    colors: ["#fff"],
    shape: "round"
  },
  {
    id: 7,
    name: "Gelang Manik (Beaded Bracelet)",
    category: "bbeads",
    desc: "Playful tapi tetap classy 🌸</br>Perpaduan warna yang lebih hidup bikin gelang ini cocok jadi statement kecil di pergelangan tanganmu.</br>Material: Glass beads premium & tali elastis tahan lama.</br>Style: Cocok untuk outfit casual, hangout, atau layering biar makin gemoy ✨",
    price: "0",
    stock: "- pcs",
    origin: "Estetik & Minimalis",
    badge: "new",
    image: "src/img/bracelet/bracelet4.jpg",
    colors: ["#fff"],
    shape: "round"
  },
  {
    id: 8,
    name: "Strap Phone",
    category: "strap",
    desc: "Simple but eye-catching 📱✨</br>Strap ini dirancang untuk kamu yang suka aksesoris clean tapi tetap punya karakter.</br>Detail: Manik pilihan + aksen lucu yang subtle.</br>Fungsi: Anti slip + bikin HP kamu lebih stylish saat dibawa kemana-mana 💗",
    price: "0",
    stock: "- pcs",
    origin: "Trendy & Pop Culture",
    badge: "new",
    image: "src/img/strap/strap2.jpg",
    colors: ["#fff"],
    shape: "round"
  },
  {
    id: 9,
    name: "Strap Phone",
    category: "strap",
    desc: "Cute overload alert 💖</br>Desain yang lebih playful dengan kombinasi warna cerah, cocok buat kamu yang suka tampil beda.</br>Detail: Mix beads + charm lucu yang bikin HP kamu makin hidup.</br>Vibe: Y2K, girly, dan super fun ✨",
    price: "0",
    stock: "- pcs",
    origin: "Trendy & Pop Culture",
    badge: "new",
    image: "src/img/strap/strap3.png",
    colors: ["#fff"],
    shape: "round"
  },
  {
    id: 10,
    name: "Strap Phone",
    category: "strap",
    desc: "Bold & expressive 🌈</br>Buat kamu yang suka tampil standout, strap ini hadir dengan warna dan desain yang lebih berani.</br>Detail: Kombinasi beads kontras + finishing rapi.</br>Perfect for: Mirror selfie, OOTD, dan jadi pusat perhatian 😤✨",
    price: "0",
    stock: "- pcs",
    origin: "Trendy & Pop Culture",
    badge: "new",
    image: "src/img/strap/strap4.webp",
    colors: ["#fff"],
    shape: "round"
  },
  // NATURAL STONE
  {
    id: 11,
    name: "Natural Stone Bracelet",
    category: "naturalstone",
    desc: "Aura alami yang tenang & elegan 🌿✨</br>Dirangkai dari batu alam pilihan dengan warna earthy yang calming, gelang ini cocok buat kamu yang suka vibes natural dan classy.</br>Material: Batu alam asli + tali elastis premium.</br>Makna: Memberikan kesan balance, grounding, dan inner peace.",
    price: "0",
    stock: "- pcs",
    origin: "Spiritual, Earthy & Calm Energy",
    badge: "new",
    image: "src/img/batualam/batualam2.jpg",
    colors: ["#fff"],
    shape: "round"
  },
  {
    id: 12,
    name: "Natural Stone Bracelet",
    category: "naturalstone",
    desc: "Simple luxury in every detail ✨</br>Butiran batu dengan pola unik bikin setiap gelang jadi satu-satunya—nggak ada yang sama.</br>Cocok untuk: Daily wear sampai acara formal.</br>Feel: Clean, mature, and quietly stunning.",
    price: "0",
    stock: "- pcs",
    origin: "Elegant, Minimal & Timeless",
    badge: "new",
    image: "src/img/batualam/batualam3.jpg",
    colors: ["#fff"],
    shape: "round"
  },
  {
    id: 13,
    name: "Natural Stone Bracelet",
    category: "naturalstone",
    desc: "Bold but grounded 🌑✨</br>Perpaduan warna batu yang lebih deep bikin look kamu makin strong tapi tetap calm.</br>Perfect for: Statement subtle tapi berkelas.",
    price: "0",
    stock: "- pcs",
    origin: "Bold, Grounded & Exclusive",
    badge: "new",
    image: "src/img/batualam/batualam4.jpg",
    colors: ["#fff"],
    shape: "round"
  },
  {
    id: 14,
    name: "Natural Stone Bracelet",
    category: "naturalstone",
    desc: "Soft energy & gentle beauty 💗</br>Warna yang lebih soft cocok banget buat kamu yang suka look feminine dan soothing.</br>Feel: Warm, calm, dan super comforting.",
    price: "0",
    stock: "- pcs",
    origin: "Soft, Feminine & Healing Vibes",
    badge: "new",
    image: "src/img/batualam/batualam5.jpg",
    colors: ["#fff"],
    shape: "round"
  },
  {
    id: 15,
    name: "Natural Stone Bracelet",
    category: "naturalstone",
    desc: "Nature meets aesthetic 🌿✨</br>Desain yang clean tapi tetap punya karakter kuat dari tekstur batu alami.</br>Perfect mix antara minimal & standout.",
    price: "0",
    stock: "- pcs",
    origin: "Natural, Aesthetic & Modern",
    badge: "new",
    image: "src/img/batualam/batualam6.jpg",
    colors: ["#fff"],
    shape: "round"
  },

  // BRACELET BEADS (lanjutan)
  {
    id: 16,
    name: "Gelang Manik (Beaded Bracelet)",
    category: "bbeads",
    desc: "Sweet & playful 💖✨</br>Kombinasi warna yang gemes bikin gelang ini cocok banget buat daily cute look kamu.</br>Perfect for: layering biar makin kiyowo!",
    price: "0",
    stock: "- pcs",
    origin: "Cute, Playful & Daily Wear",
    badge: "new",
    image: "src/img/bracelet/bracelet5.jpg",
    colors: ["#fff"],
    shape: "round"
  },
  {
    id: 17,
    name: "Gelang Manik (Beaded Bracelet)",
    category: "bbeads",
    desc: "Soft tone, big charm 🌸</br>Warna-warna pastel yang calming tapi tetap eye-catching.</br>Feel: Calm, girly, and elegant.",
    price: "0",
    stock: "- pcs",
    origin: "Pastel, Soft Girl & Aesthetic",
    badge: "new",
    image: "src/img/bracelet/bracelet6.jpg",
    colors: ["#fff"],
    shape: "round"
  },
  {
    id: 18,
    name: "Gelang Manik (Beaded Bracelet)",
    category: "bbeads",
    desc: "Tiny detail, big impact ✨</br>Walaupun simple, gelang ini tetap bikin look kamu naik level instantly.</br>Style: Clean, modern, dan versatile.",
    price: "0",
    stock: "- pcs",
    origin: "Minimal, Clean & Modern",
    badge: "new",
    image: "src/img/bracelet/bracelet7.jpg",
    colors: ["#fff"],
    shape: "round"
  },
  {
    id: 19,
    name: "Gelang Manik (Beaded Bracelet)",
    category: "bbeads",
    desc: "Color pop energy 🌈</br>Buat kamu yang suka warna cerah dan playful, ini wajib banget.</br>Perfect for: fun outfit & OOTD standout!",
    price: "0",
    stock: "- pcs",
    origin: "Vibrant, Fun & Youthful",
    badge: "new",
    image: "src/img/bracelet/bracelet8.jpg",
    colors: ["#fff"],
    shape: "round"
  },

  // BAG CHARM (lanjutan)
  {
    id: 20,
    name: "Bag Charm",
    category: "bagcharm",
    desc: "Tiny charm, big personality 🎒✨</br>Tambahin sentuhan unik ke tas kamu biar nggak boring lagi.</br>Style: playful dan standout!",
    price: "0",
    stock: "- pcs",
    origin: "Playful, Cute & Statement",
    badge: "new",
    image: "src/img/bagcharm/bagcharm2.jpg",
    colors: ["#fff"],
    shape: "round"
  },
  {
    id: 21,
    name: "Bag Charm",
    category: "bagcharm",
    desc: "Street style vibes 😤✨</br>Desain lebih bold cocok buat kamu yang suka tampil beda.</br>Feel: edgy tapi tetap fun.",
    price: "0",
    stock: "- pcs",
    origin: "Street, Bold & Expressive",
    badge: "new",
    image: "src/img/bagcharm/bagcharm3.jpg",
    colors: ["#fff"],
    shape: "round"
  },
  {
    id: 22,
    name: "Bag Charm",
    category: "bagcharm",
    desc: "Soft but noticeable 💗</br>Manis tapi tetap punya presence yang bikin tas kamu makin hidup.</br>Perfect for: daily aesthetic look.",
    price: "0",
    stock: "- pcs",
    origin: "Soft, Aesthetic & Chic",
    badge: "new",
    image: "src/img/bagcharm/bagcharm4.jpg",
    colors: ["#fff"],
    shape: "round"
  },
  {
    id: 23,
    name: "Bag Charm",
    category: "bagcharm",
    desc: "Layered texture magic ✨</br>Kombinasi ukuran dan bentuk manik bikin charm ini lebih dimensional dan unik.</br>Super eye-catching!",
    price: "0",
    stock: "- pcs",
    origin: "Layered, Unique & Artistic",
    badge: "new",
    image: "src/img/bagcharm/bagcharm5.jpg",
    colors: ["#fff"],
    shape: "round"
  },
  {
    id: 24,
    name: "Bag Charm",
    category: "bagcharm",
    desc: "Cute overload incoming 💖</br>Desain super gemoy yang langsung bikin mood naik.</br>Perfect for: girly & kawaii lovers!",
    price: "0",
    stock: "- pcs",
    origin: "Kawaii, Cute & Fun",
    badge: "new",
    image: "src/img/bagcharm/bagcharm6.jpg",
    colors: ["#fff"],
    shape: "round"
  },
  {
    id: 25,
    name: "Bag Charm",
    category: "bagcharm",
    desc: "Minimal but stylish ✨</br>Nggak terlalu ramai tapi tetap punya karakter yang kuat.</br>Clean look enjoyer pasti suka ini.",
    price: "0",
    stock: "- pcs",
    origin: "Minimal, Stylish & Clean",
    badge: "new",
    image: "src/img/bagcharm/bagcharm7.jpg",
    colors: ["#fff"],
    shape: "round"
  },

  // STRAP PHONE (lanjutan)
  {
    id: 26,
    name: "Strap Phone",
    category: "strap",
    desc: "Effortlessly cute 📱💖</br>Desain simpel tapi tetap bikin HP kamu keliatan lebih hidup.</br>Perfect balance antara fungsi & style.",
    price: "0",
    stock: "- pcs",
    origin: "Simple, Cute & Functional",
    badge: "new",
    image: "src/img/strap/strap5.jpg",
    colors: ["#fff"],
    shape: "round"
  },
  {
    id: 27,
    name: "Strap Phone",
    category: "strap",
    desc: "Statement in your hand ✨</br>Lebih bold dan expressive, cocok buat kamu yang suka tampil beda.</br>OOTD + mirror selfie approved 😤💗",
    price: "0",
    stock: "- pcs",
    origin: "Bold, Trendy & Eye-catching",
    badge: "new",
    image: "src/img/strap/strap6.jpg",
    colors: ["#fff"],
    shape: "round"
  }
];